Style/Documentation: 
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Rails:
  Enabled: true
Metrics/LineLength:
  Max: 120
AllCops:
  Exclude:
    - config/initializers/secret_token.rb